server:
  port: 8020
spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://localhost:3306/clientdb?autoReconnect=true&useSSL=false&serverTimezone=America/Lima
    username: veronica
    password: 1234
  main:
    banner-mode: "off"
logging:
  config: classpath:logging/logback.xml